FROM node:8

#FROM here we load our applications code in, therefore the prvious docker
# "layer" thats been cached will be used if possible
WORKDIR /usr/src/app

#use changes to package.json to force docker not use the cache
#when we change our appliction's nodejs dependencies:
COPY package.json /tmp/package.json
RUN cd /tmp && npm install
RUN mkdir -p /usr/src/app && cp -a /tmp/node_modules /usr/src/app

COPY . /usr/src/app

ENV PORT=8080
EXPOSE 8080

#Run the code
CMD ["npm", "start"]
